### ISSUE TITLE
Segfault when calling .destroy() on element while iterating querySelectorAll()

### ISSUE THREAD

**Issue by forbjok** [eBookingServices/htmld#30]
The following will cause a segfault from v0.3.1, up to and including the current master branch of htmld.
```d
foreach(e; document.querySelectorAll("script", document.root)) {
    e.destroy();
}
```

Minimal reproduction: [htmld-segfault-repro.zip](https://github.com/eBookingServices/htmld/files/1855534/htmld-segfault-repro.zip)

Tested with DMD v2.079 and LDC2 v1.8.0.

I don't know whether this would be considered a bug, or whether the fact that it worked before was just an accident, but I do know it works fine in v0.2.19 and older.

Currently, as a workaround, I've changed my code to just add all elements to an array and iterate and destroy each one from the array afterwards.

UPDATE:
I did a bit more testing, and the exact commit that introduces the segfault is https://github.com/eBookingServices/htmld/commit/8fe2134d623ef57f57a4fac3f529e7391f6a4c89.

**Comment by marcioapm** [comment]
Thanks for reporting! I did some quick investigation and the reason it used to work is because the old allocator wasn't zeroing out disposed memory, combined with detachFast() not touching own memory, so after the node was deleted it was still pointing to valid untouched memory. I suspect if you were to allocate a new node inside the loop, i.e. re-use the just freed memory, it would no longer work as expected.
